# azure-pipelines.yml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        steps:
          - task: UseJava@1
            inputs:
              versionSpec: '11' # Specify the Java version you need
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - script: |
              echo "Cloning repository..."
              git clone https://github.com/SAITEJABURRA33/dicet_tv.git
            displayName: 'Git Clone'

          - script: |
              echo "Building with Maven..."
              cd your-repo-directory
              mvn clean install
            displayName: 'Maven Build'

