# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

stages:
  - stage: Build
    jobs:
      - job: MavenBuild
        steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '22'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

          - script: |
              echo "Cloning repository..."
              git clone https://your-repo-url.git
            displayName: 'Git Clone'

          - script: |
              echo "Building with Maven..."
              cd your-repo-directory
              mvn clean install
            displayName: 'Maven Build'